### ISSUE TITLE
Real-Time IPA Expiry Tagging in Dispute Module

### ISSUE THREAD

**Issue by kingster-will** [storyprotocol/protocol-core-v1#68]
Please the requirements https://www.notion.so/storyprotocol/Expiration-Term-PIL-9e1c3b3945b74d10987dae6eafc245bb?pvs=4

Here's the revised text with corrections and improvements to the syntax and phrasing:

The dispute module needs to support tagging of expired IPAs. Both the Royalty Module and the Licensing Module should verify the tag. To set and verify the expiration through the DisputeModule, consider the following approach:  
We can introduce a new function in the DisputeModule called `checkTagAndExpiration(address ipId) returns (bool)`. This function will verify existing tags and also check the expiration of the IPA, applying an "EXPIRED" tag if the IPA has expired.  
Subsequently, all other functions or external applications should call this function before proceeding with their operations. This ensures that the tagging remains up-to-date and reflective of real-time status.

**Comment by jdubpark** [comment]
Noting that a public `checkTagAndExpiration` with a side effect (setting a dispute tag) means external contracts can't use it in view functions, which reduces composability (if we expect this to be called by external contracts too).

**Comment by Spablob** [comment]
I guess I would need to know on licensing side:
1. which licensing side functions need the expiration restriction?
2. since the time only starts on burning a license in which licensing side function should the timer start?
3. (not sure) is there a way to register a IPAsset without burning the license? If there is, how can we prevent people to circumvent the expiration time when they don't burn the license?
